### ISSUE TITLE
Is it possible to use dynamic selector names?

### ISSUE THREAD

**Issue by erichonkanen** [simplabs/ember-test-selectors#165]
In our project we have a use case for dynamic selector names but unfortunately it doesn't seem intuitive... We've switched to using a different pattern e.g. `<button tid="data-test-dynamic-name-input">`, but I'm wondering if this is something possible via this library?

**Comment by marcoow** [comment]
No, it's not possible to change the `data-test-` prefix to anything else. What's your motivation for using `<button tid="data-test-dynamic-name-input">` vs. `<button data-test-dynamic-name-input>`?

**Comment by erichonkanen** [comment]
hey, so yeah the pattern in the project has been `data-test-thing=true`, to be honest I didn't even think of making it e.g. `data-test-input="username"`; the motivation was to make a selector that includes the dynamic name and as you mentioned you can't set the attribute name like that... could probably use the pattern of `data-test-input="username"` to avoid two patterns in the project

**Comment by ChrizzDF** [comment]
Hi! I'm just facing a similar challenge where dynamic data-test attributes were quite helpful imho:

Assuming I have ONE component that is a table to show users. I'm reusing it for Friends, Colleagues, Managers etc.

`{{users-table users=friends}}`
`{{users-table users=colleagues}}`
`{{users-table users=managers}}`

So inside, I want to have data-test attributes like this:
`data-test-users-table-row-friend="0"`
`data-test-users-table-row-friend="1"`

`data-test-users-table-row-colleague="0"`
`data-test-users-table-row-colleague="1"`

`data-test-users-table-row-manager="0"`
`data-test-users-table-row-manaer="1"`

Because I'm rendering all these tables on one page and have acceptance-test for checking the presence of these rows, they shouldn't have the same data-test attribute because I couldn't differentiate then.

Can you see my point? How should I solve this issue with only having a dynamic value?

**Comment by Turbo87** [comment]
`data-test-users-table-row-type="manager" data-test-users-table-row-number="0"` would be a potential solution

**Comment by ChrizzDF** [comment]
This I also had in mind, but still had hope not having to use two data-test attributes on one single element 😆

Thanks!
